apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: static-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "" # Explicitly disabled to match PV
  volumeName: static-pv
  resources:
    requests:
      storage: 1Gi
